### ISSUE TITLE
Accept unicode strings as input

### ISSUE THREAD

**Issue by Huji** [mhajiloo/persiantools#10]
The `replace` method in `utils.py` starts with checking if the input is of type `string`. This is not ideal because in python 2.x the strings are often of type `unicode` and that renders some of the functionalities of persiantools unusbale.

For instance, this won't work in persiantools:

```
digits.fa_to_en(u'۱۲۳۴')
```

This can be address by allowing the `unicode` data-type [here](https://github.com/mhajiloo/persiantools/blob/e14d510d6d952e60d796a9bfbde71fa605bb659f/persiantools/utils.py#L6)

**Comment by mhajiloo** [comment]
It works now 🙏🏻
