### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by GreatBahram** [mhajiloo/persiantools#11]
https://github.com/mhajiloo/persiantools/blob/a88112b5955cb8214e84467357bee61cc01242ba/persiantools/utils.py#L19
```python
value = int(value)
```

**Comment by mhajiloo** [comment]
If `value` defines `__int__()`, `int(value)` returns `value.__int__()`. If `value` defines `__trunc__()`, it returns` value.__trunc__()`. For floating point numbers, this truncates towards zero!
