### ISSUE TITLE
Why the result is not the same in Python and Sublime Text 3?

### ISSUE THREAD

**Issue by 0xdolan** [mhajiloo/persiantools#6]
When testing your module, the result in **Sublime Text 3** and **Python IDLE** is the same and _**none**_ of them show the **Day** name (for instance: Jomeh), but when using the **Python** or **CMD** directly to work with the same code, it works fine!
Test:

`from persiantools.jdatetime import JalaliDate`
`from datetime import datetime`
`print(datetime.today())  # Output: 2018-08-24 12:33:20.700418`
`print(JalaliDate.today())  # Output: 1397-06-02`
`print(JalaliDate(1369, 7, 1))  # Output: 1369-07-01`

![1](https://user-images.githubusercontent.com/18519747/44578301-fbbc6f00-a79b-11e8-872c-ab61fd5b8284.JPG)
![2](https://user-images.githubusercontent.com/18519747/44578302-fbbc6f00-a79b-11e8-96ef-b9f758b921d0.JPG)

**Comment by mhajiloo** [comment]
when using cmd => [`__repr__`](https://github.com/mhajiloo/persiantools/blob/e14d510d6d952e60d796a9bfbde71fa605bb659f/persiantools/jdatetime.py#L281) 
when using `print` =>  [`__str__` ](https://github.com/mhajiloo/persiantools/blob/e14d510d6d952e60d796a9bfbde71fa605bb659f/persiantools/jdatetime.py#L252)
